[project]
name = "test-tika"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "comtypes>=1.4.12",
    "pathlib>=1.0.1",
    "polars>=1.33.1",
    "python-docx>=1.2.0",
    "streamlit>=1.50.0",
    "tika>=3.1.0",
]
